version: '3.8'

services:
  server:
    build: .
    container_name: servidor_relogio
    command: python server.py
    ports:
      - "12345:12345"

  client1:
    build: .
    container_name: cliente_relogio1
    command: python client.py
    depends_on:
      - server

  client2:
    build: .
    container_name: cliente_relogio2
    command: python client.py
    depends_on:
      - server

  client3:
    build: .
    container_name: cliente_relogio3
    command: python client.py
    depends_on:
      - server

  client4:
    build: .
    container_name: cliente_relogio4
    command: python client.py
    depends_on:
      - server

  client5:
    build: .
    container_name: cliente_relogio5
    command: python client.py
    depends_on:
      - server